### ISSUE TITLE
Promise start running since created but not when await/then

### ISSUE THREAD

**Issue by airicyu** [menocomp/chunk-promise#2]
Hi, I write this not becoz of bugs but just want to ask for some clarification.

As I know, a promise begin to run when we create the promise object via "new Promise(....)", but not when we await/then the promise object.

So, if the use case of the library is that the user would create some promises, and then pass through this library to control the concurrency, it should be failed to do what it intended to be.
Because the promises would just run when user created them before passing to this library's code....
The library might just able to do "await/then" concurrently but have nothing to do with the promises real running concurrency....

**Comment by maxmartynov** [comment]
Please take a look at the [example](https://github.com/menocomp/chunk-promise#1-run-list-of-promises-in-chunks-using-promiseall). The `chunkPromise()` function expects an **array of functions** as the first argument (not an array of Promises). Each function in this array is something like a wrapper function that should return a Promise. And each **new Promise will be run after its wrapper function is executed**. This is what the library does: it executes the wrapper functions in some order.

**Comment by airicyu** [comment]
oh I get it, thx
